name: release validation

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  validate:
    uses: EnVisione/.github/.github/workflows/release-validation.yml@52eb01f2a9d378693156c88e03e41dcb9f5e25bb
    with:
      shared-ref: "52eb01f2a9d378693156c88e03e41dcb9f5e25bb"
      java-version: "25"
