name: release validation

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  validate:
    uses: MCEnvision/.github/.github/workflows/release-validation.yml@ec831efc8265543929ef11c5569d07d5ca095b56
    with:
      shared-ref: "ec831efc8265543929ef11c5569d07d5ca095b56"
      java-version: "25"
